# Taskfile is used to run common tasks when developing the application.
# Check : https://taskfile.dev/usage/
version: "3"
silent: true
vars:
  REPORTS_DIR: reports
  GO_MODULES:
    sh: git ls-files "*/go.mod" "go.mod" | xargs dirname | sort
tasks:
  default:
    cmds:
      - task -l

  lint:
    desc: Lints Go code using golangci-lint
    cmds:
      - for:
          var: GO_MODULES
        cmd: cd {{.TASKFILE_DIR}}/{{.ITEM}} && echo "Run Linting on module {{.ITEM}}" && golangci-lint run --fix

  fmt:
    desc: Formats all code
    cmds:
      - for:
          var: GO_MODULES
        cmd: gofumpt -l -w {{.TASKFILE_DIR}}/{{.ITEM}}

  test:
    desc: Runs tests for all modules
    cmds:
      - for:
          var: GO_MODULES
        cmd: |
          echo "Running tests for module {{.ITEM}}"
          LABEL=$([ "{{.ITEM}}" = "." ] && echo "root" || echo "{{.ITEM}}" | tr "/" "-")
          mkdir -p {{.TASKFILE_DIR}}/{{.REPORTS_DIR}}/$LABEL
          cd {{.TASKFILE_DIR}}/{{.ITEM}} && gotestsum --format="testname" \
            --junitfile {{.TASKFILE_DIR}}/{{.REPORTS_DIR}}/$LABEL/unit-tests.xml \
            --jsonfile {{.TASKFILE_DIR}}/{{.REPORTS_DIR}}/$LABEL/unit-tests.json \
            -- -coverprofile={{.TASKFILE_DIR}}/{{.REPORTS_DIR}}/$LABEL/cover.out -covermode=atomic \
            ./...

  docgen:
    desc: Generates godoc documentation for all packages
    cmds:
      - for:
          var: GO_MODULES
        cmd: cd {{.TASKFILE_DIR}}/{{.ITEM}} && gomarkdoc --output "{{ print `{{.Dir}}/README.md` }}" --exclude-dirs ".devenv/..." ./...

  tidy:
    desc: Runs go mod tidy for all modules
    cmds:
      - for:
          var: GO_MODULES
        cmd: cd {{.TASKFILE_DIR}}/{{.ITEM}} && go mod tidy
