name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  packages: write

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      root: ${{ steps.filter.outputs.root }}
      tracing: ${{ steps.filter.outputs.tracing }}
      db: ${{ steps.filter.outputs.db }}
      shared: ${{ steps.filter.outputs.shared }}
    steps:
      - uses: actions/checkout@v6

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            shared:
              - '.github/workflows/**'
              - 'go.work'
              - 'go.work.sum'
              - '.golangci.yml'
            tracing:
              - 'tracing/**'
              - '!tracing/CHANGELOG.md'
            db:
              - 'db/**'
              - !'db/CHANGELOG.md'
            root:
              - '**'
              - '!tracing/**'
              - '!db/**'

  root:
    name: Root
    needs: changes
    if: |
      needs.changes.outputs.shared == 'true' ||
      needs.changes.outputs.root == 'true' ||
      github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/_module-ci.yml
    with:
      module: .
      label: root
      go-mod: go.mod
    secrets: inherit

  tracing:
    name: Tracing
    needs: changes
    if: |
      needs.changes.outputs.shared == 'true' ||
      needs.changes.outputs.tracing == 'true' ||
      github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/_module-ci.yml
    with:
      module: tracing
      label: tracing
      go-mod: tracing/go.mod
    secrets: inherit

  db:
    name: DB
    needs: changes
    if: |
      needs.changes.outputs.shared == 'true' ||
      needs.changes.outputs.root == 'true' ||
      needs.changes.outputs.db == 'true' ||
      github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/_module-ci.yml
    with:
      module: db
      label: db
      go-mod: db/go.mod
    secrets: inherit
