name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - published

env:
  GO_VERSION: 1.22
  GOTESTSUM_VERSION: 1.11.0
  GOLANGCI_LINT_VERSION: v1.60.1
  CI: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  packages: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false # Conflicts with GolangCI, if enabled

      - name: GolangCI
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          only-new-issues: true

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup gotestsum
        uses: autero1/action-gotestsum@v2.0.0
        with:
          gotestsum_version: ${{ env.GOTESTSUM_VERSION }}

      - name: Run tests
        run: |
          gotestsum --junitfile reports/unit-tests.xml --jsonfile reports/unit-tests-results.json -- -race -covermode=atomic -coverprofile=cover.txt ./...

      - name: Generate test report
        uses: dorny/test-reporter@v1
        if: ${{ !cancelled() }}
        with:
            name: Unit Tests Report
            path: 'reports/*.xml'
            reporter: jest-junit

      - name: Upload test report artifact
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: unit-test-report
          path: reports

      - name: Upload code coverage report to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: cover.txt

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./reports/unit-tests.xml

