name: Release
on:
  push:
    branches: [main]

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Publish Release
        uses: robgonnella/releasaurus/action@4ddec7b3e1e8f04ee789b31d892f7d2f40145b15 # v1.2.3
        with:
          command: release
          command_args: >-
            --forge github
            --repo ${{ github.server_url }}/${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release PR
        uses: robgonnella/releasaurus/action@4ddec7b3e1e8f04ee789b31d892f7d2f40145b15 # v1.2.3
        with:
          command: release-pr
          command_args: >-
            --forge github
            --debug
            --repo ${{ github.server_url }}/${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
